### ISSUE TITLE
Navigation bar on top of fullscreen content

### ISSUE THREAD

**Issue by vibrog** [robflaherty/html-slideshow#2]
Inserting a full sized (`height:100%;width:100%;`) iframe/embed/video element makes the navbar inaccessible. `z-index:-1;` does not work as focus is moved to the an element outside the actual page content.

**Comment by robflaherty** [comment]
Hey,
What browser(s) were you seeing this in?  I tested with an iframe and it works correctly in Chrome and Firefox. See here:

http://www.ravelrumba.com/misc/tests/html-slideshow-issue2/example/slideshow.html

Or maybe I'm misunderstanding the bug?

**Comment by vibrog** [comment]
ah, i used absolute positioning:

```
embed,video,iframe {
  position: absolute; left:0; top:0;
  width:100%; height:100%;
}
```

with this the navbar will be inaccessible, add `z-index:-1;` and the iframe will become inaccessible.

**Comment by robflaherty** [comment]
Ah, got it. I see two parts to the problem.  One is the z-index problem, which I think I've fixed here (yeah?): 
http://www.ravelrumba.com/misc/tests/html-slideshow-issue2-2/example/slideshow.html

The other is the focus problem where the iframe can grab the focus and disable the key controls. I'll work on that next.

Thanks!

**Comment by robflaherty** [comment]
How's this?
http://www.ravelrumba.com/misc/tests/html-slideshow-issue2-3/example/slideshow.html

**Comment by vibrog** [comment]
I can't really test it fully:
With all your examples here, the navbar are always visible.
(Chromium, Firefox)

**Comment by robflaherty** [comment]
Yeah, I had the navbar option setting set to the default. I switched it back to hidden and it all seems to work fine.  I'm going to ahead and consider this resolved.

Thanks again!

**Comment by vibrog** [comment]
nice, note that the navbar won't show on plugin content, but it captures user input (changes to hand on mouseover, mouse click and keyboard press).

```
<embed src="video/example.mov" type="video/quicktime"/>
```

**Comment by robflaherty** [comment]
Working with z-index and plugin content can be tricky. I'm not sure about embedded Quicktime video, but with Flash there are factors affecting z-index layering like the `wmode` parameter in the embed code.

This seems like a minor issue... But if you disagree and feel it's a serious problem let me know.
