### ISSUE TITLE
Can this work on mobile?

### ISSUE THREAD

**Issue by smcameron** [robflaherty/html-slideshow#7]
Hi, first, thanks for this, I have found it very useful for presentations.

However, I noticed I can't figure out how to navigate those presentations with, say, Chrome on Android.  Can't figure out how to use the arrow keys to navigate.

Is there a way to make the presentations viewable on mobile?

Thanks.

**Comment by robflaherty** [comment]
Hey,

This is an old project and is no longer maintained. There are many far superior options now and I'd recommend you check out those instead :)
